'''Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.'''
#Answer: 4613732


import time, itertools
from eulertools import fib_gen


def solve():
    even_nums = (x for x in fib_gen() if x % 2 == 0)
    print sum(list(itertools.takewhile(lambda x: x < 4000000, even_nums)))


if __name__ == '__main__':
    start = time.clock()
    solve()
    print 'Time elapsed:', (time.clock() - start)

    
